[package]
name = "quickwit-directories"
version = "0.3.1"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                                                         # For a commercial, license, contact hello@quickwit.io
description = "Crate containing all of the custom tantivy Directory used in quickwit"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
instant = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
serde_json = { workspace = true }
tantivy = { workspace = true, features = ["quickwit"] }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true }

quickwit-cache = { workspace = true }
quickwit-common = { workspace = true }
quickwit-storage = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, default-features = false, features = ["time"] }

[features]
storage = ["quickwit-common/uri", "quickwit-storage"]
tokio-time = ["quickwit-cache/tokio-time"]
